### ISSUE TITLE
Variablen Standardisierung

### ISSUE THREAD

**Issue by MilanKosticKIT** [MilanKosticKIT/BetriebssystemeUebung#10]
Bei den Variablen sollten wir einheitliche Typen verwenden. Folgende Möglichkeiten sind, bis jetzt, vorhanden:
 - u_int...
 - uint...
 - size_t

Wenn die ...int... Varianten benutzt werden sollen gibt es noch das Problem der Größe (16,32,...512?!?!)

**Comment by murmal** [comment]
uint16_t
