### ISSUE TITLE
FAT // iterateFAT()

### ISSUE THREAD

**Issue by HannesIlly** [MilanKosticKIT/BetriebssystemeUebung#18]
iterateFAT() sollte eventuell eine list<uint16_t> zurückgeben.
Wenn das geändert wird muss es in .cpp / .h geändert werden.

Ich habe auch an ein paar Stellen in fat.h den Datentyp zu uint16_t geändert.
Genaue Funktionalität/Implementierung ist mir leider nicht bekannt.

**Comment by murmal** [comment]
habs geändert
