### ISSUE TITLE
FUSE-Methoden implementieren

### ISSUE THREAD

**Issue by murmal** [MilanKosticKIT/BetriebssystemeUebung#24]
Die in myfs.cpp erwähnten Methoden zu Fuse anschauen:   
- [x] fuseGetattr (Metadaten zurückgeben)
- [x] fuseOpen (Datei öffnen)
- [x] fuseRelease (Datei schliessen)
- [x] fuseRead (Daten lesen)
- [x] fuseReaddir
- [x] fuseInit

Unser Verzeichnis kann auch beim Initialisieren/Freigeben der Containerdatei geöffnet bzw. geschlossen werden.
- [x] fuseOpendir
- [x] fuseReleasedir

Bei open und close müssen wir schauen, ob wir speichern müssen, welche Dateien offen sind.

**Comment by HannesIlly** [comment]
Muss jetzt noch getestet werden.
