### ISSUE TITLE
Klassenvarablen Initialisierung und Löschung bearbeiten

### ISSUE THREAD

**Issue by MilanKosticKIT** [MilanKosticKIT/BetriebssystemeUebung#25]
Klassenvariablen sollen mit **new** erzeugt werden, um auf dem Heap zu landen. D.h. man erhält einen Pointer auf die Variable.
Desweiteren sollen wir für jede Datenstruktur die Variablen im destruktiv löschen.
- [ ] dmap
- [ ] fat
- [ ] root
- [ ] filesystemIO
- [ ] mkfs.myfs

**Comment by HannesIlly** [comment]
Bei Arrays ist das anscheinend nicht so einfach.
Soll jeder so machen wie er will, hauptsache es funktioniert, ist gekapselt und es gibt keine Speicherlecks.
