### ISSUE TITLE
filesystemIO Klasse

### ISSUE THREAD

**Issue by MilanKosticKIT** [MilanKosticKIT/BetriebssystemeUebung#28]
Wenn die filesystemIO Klasse verwendet wird, um etwas in das Blockdevice zu schreiben, gibt es Fehler. 
Diese Fehler sehen je nach IDE etwas anders aus.

**Comment by HannesIlly** [comment]
Hier steht glaub ich was sinnvolles drin, aber ich glaube wir sollten dann noch jemand fragen:
https://bytefreaks.net/programming-2/c/c-undefined-reference-to-templated-class-function

**Comment by HannesIlly** [comment]
Implementierung wurde in den Header verschoben.
