### ISSUE TITLE
DMap // Dmap.getAll does not write the data in the return value

### ISSUE THREAD

**Issue by MilanKosticKIT** [MilanKosticKIT/BetriebssystemeUebung#35]
The method dmap.getAll(char * p) does not write the data of dmapValues into p.

**Comment by HannesIlly** [comment]
Die Zuweisung des gegebenen Pointers auf unser internes Array funktioniert nicht, da der gegebene Pointer eine Kopie ist (wegen Methodenparameter).
Das manuelle Kopieren aller Werte ist jetzt implementiert.
