### ISSUE TITLE
DMap // Behavior of dmap.clear(uint16_t clearAddress) with an invalid address

### ISSUE THREAD

**Issue by MilanKosticKIT** [MilanKosticKIT/BetriebssystemeUebung#36]
How should dmap.cleat(unnit16_t clearAddress) handle a call with an address that is:
- [x] to big
- [x] to small (negative) -> Because we are using unsigned int this is not really a problem of the implementation.

**Comment by HannesIlly** [comment]
Da wir uint16_t benutzen kann der gegebene Wert nicht negativ sein und ebenfalls nicht unseren Wertebereich überschreiten.
