### ISSUE TITLE
DMap // Behavior of dmap.set(uint16_t setAddress)

### ISSUE THREAD

**Issue by MilanKosticKIT** [MilanKosticKIT/BetriebssystemeUebung#37]
How should dmap.set(unnit16_t setAddress) handle a call:
- [x]  with an address that is to big.
- [ ] where the address is already set.

**Comment by HannesIlly** [comment]
Wegen uint16_t kann die gegebene Adresse nicht den gültigen Wertebereich überschreiben.
Aktuell ist es denk ich ok, wenn die Methode bei erneutem setzen keinen Fehler zurückgibt, könnte man in Zukunft aber evtl. ändern.

**Comment by HannesIlly** [comment]
Ich denke das passt aktuell so wie es ist. Wenn es später Probleme gibt muss man dann halt nochmal ein Ticket schreiben.
