### ISSUE TITLE
FAT // Implementation of terminator character

### ISSUE THREAD

**Issue by MilanKosticKIT** [MilanKosticKIT/BetriebssystemeUebung#38]
The terminator character is currently intended to be represented by a "-1". Bt this character is saved in an uint_16 (unsigned). So the real value is 65535.
This is a problem because this is an actual address.

**Comment by MilanKosticKIT** [comment]
Solved with adaption with the fat array from uint16_t to uint32_t

**Comment by murmal** [comment]
lösung: möglichen Adressen/Blöcke von 65536 auf 65535 zu reduzieren und somit den verbleibenden Wert der uint16_t als Terminator character nutzen.
