### ISSUE TITLE
FAT // Größe der FAT reduzieren

### ISSUE THREAD

**Issue by MilanKosticKIT** [MilanKosticKIT/BetriebssystemeUebung#39]
## Ursachen
 - Darstellung des letzten Blockes einer Datei als -1 in der FAT Tabelle
 - Gespeichert als **u**int16_t
 - Gesamter benötigter Adressraum geht bis 2^16 = 65.536 = uint16_t
## Folge
Das Terminator "Symbol" war gleichzeitig ein tatsächlich vorhandene Adresse, wodurch diese immer wieder als folgendes Array angehängt wurde.  
## (Vorläufige) Lösung des obigen Problems
Vergrößerung des Variablentyps auf uint32_t. Dadurch zeigt die -1 nicht mehr auf eine Tatsächliche Adresse. Dadurch ist die FAT auf 512 Blöcke angewachsen (alle Superblock, DMap und Root zusammen brachen *nur* 81 Blöcke)

**Comment by HannesIlly** [comment]
Ich wäre dafür, die möglichen Adressen/Blöcke von 65536 auf 65535 zu reduzieren und somit den verbleibenden Wert der uint16_t als Terminator zu nutzen.

**Comment by murmal** [comment]
> Ich wäre dafür, die möglichen Adressen/Blöcke von 65536 auf 65535 zu reduzieren und somit den verbleibenden Wert der uint16_t als Terminator zu nutzen.

fänd ich eigentilch ne ziemlich elegante lösung, würd das so machen.

**Comment by MilanKosticKIT** [comment]
Also es muss gemacht werden den die DMAP wirft jetzt seit deiner angepassten Version murmal einige Fehler.

**Comment by HannesIlly** [comment]
Sollte passen.
