### ISSUE TITLE
FAT // addToFAT

### ISSUE THREAD

**Issue by HannesIlly** [MilanKosticKIT/BetriebssystemeUebung#40]
Die Tests die ich gerade geschrieben habe sind nicht erfolgreich. So wie ich das interpretiere ist es irgendwas mit dem Speicher.
Eventuell müssten nochmal die Tests überprüft werden, ich denke allerdings, dass es an dieser Methode liegt, also sollte sie überprüft werden und ggf gefixt.
(alternativ könnte man auch die Methode addToFAT(int **block**, int nextBlock), die immer zu dem gegebenen Block den nächsten speichert implementieren)

**Comment by murmal** [comment]
gucks mir sonntag mal an

**Comment by murmal** [comment]
habs soweit gefixt, die tests laufen alle durch, außer der unfertige

**Comment by murmal** [comment]
die methode addToFAT(int block, int nextBlock) wurde durch addNexttToFAT(uint16_t currentLastBlock, uint16_t nextBlock) ersetzt, da man vorher beim erstellen jedesmal durch die liste der blocks iterieren musste, was die performace ziemlich gefickt hat.
jetzt ist es schnell, da der aktuell letzte block einer datei gespeichert wird und so nicht mehr durch die ganze datei iteriert werden muss.
