### ISSUE TITLE
Test // FAT // Require

### ISSUE THREAD

**Issue by HannesIlly** [MilanKosticKIT/BetriebssystemeUebung#41]
Bei einigen Tests in test-fat steht folgendes:
``REQUIRE(memcmp(...));``
Da memcmp bei gleichem Inhalt 0 zurückgibt, ergibt sich hiermit als boolean false.
Ist vermutlich nicht so gedacht.

**Comment by MilanKosticKIT** [comment]
Danke für die Beobachtung.
War tatsächlich ein Fehler ich drüber.

**Comment by MilanKosticKIT** [comment]
Alle vorkommen von memcpm wurden bei bedarf korrigiert.
