### ISSUE TITLE
MKFS.MYFS // Ausgabe

### ISSUE THREAD

**Issue by MilanKosticKIT** [MilanKosticKIT/BetriebssystemeUebung#45]
Wenn das Dateisystem gemountet wird, ist es nicht möglich die Stats zu enthaltenen Dateien mittels ls -l auszulesen. Man bekommt stattdessen lauter Fragezeichen.
Im Log bei der Stat-Abfrage dieser Datei: <kbd>to do: noch einfügen</kbd>

**Comment by HannesIlly** [comment]
Das liegt daran, dass das Verzeichnis auch stats hat, wir aber bisher nur für unsere Dateien die stats gespeichert haben.

**Comment by HannesIlly** [comment]
Die Verzeichnisstats werden jetzt in der Root gespeichert.
