### ISSUE TITLE
Root // createEntry

### ISSUE THREAD

**Issue by HannesIlly** [MilanKosticKIT/BetriebssystemeUebung#46]
Wenn ein Eintrag erstellt wird, wird der firstBlock in den fileStats nicht gesetzt. Da der bisher vorhandene Wert aber auf einen Block verweist, sollte man firstBlock vielleicht auf `FAT_TERMINATOR` setzen.

**Comment by HannesIlly** [comment]
Dafür sollte evtl noch ein Test-Case geschrieben werden.

**Comment by MilanKosticKIT** [comment]
Wenn ein Eintrag erstellt wird, wird der firstBlock in der fileStats auf `FAT_TERMINATOR`gesetzt.
