### ISSUE TITLE
Fuse // basename

### ISSUE THREAD

**Issue by HannesIlly** [MilanKosticKIT/BetriebssystemeUebung#48]
Ich habe gerade in fuseGetattr() eine konvertierung von ``path`` zu dessen basename (z.B. "/test.txt" --> "test.txt") implementiert.
Das soll in allen Fuse-Methoden gemacht werden:
 - [x] getAttr()
 - [x] fuseMakeNod
 - [x] fuseUnlink
 - [x] fuseRead
 - [x] fuseOpen
 - [x] fuseWrite
 - [x] fuseRelease
 - [x] fuseCreate

**Comment by HannesIlly** [comment]
Viel einfacher geht das, indem man folgendes macht:
`char* name = path + 1;`

**Comment by MilanKosticKIT** [comment]
Hannes hat all die Arbeit vollbracht.
