### ISSUE TITLE
MYFS // Fuse Methoden implementieren

### ISSUE THREAD

**Issue by MilanKosticKIT** [MilanKosticKIT/BetriebssystemeUebung#53]
Wie in #24 sollen Fuse Methoden implementiert werden.
Im Einzelnen:
 - [x] fuseWrite (Daten schreiben)
   - [x] Zeiten anpassen
      - [x] aTime (Letzter Zugriff auf Datei)
      - [x] cTime (Beim Erstellen einer Datei)
      - [x] mTime (Letzte aenderung an der Datei)
 - [x] fuseMknod (Datei erstellen)
    Bei der Erstellung einer Datei ist der erste Block noch nicht gesetzt. Dies muss unbedingt getan werden! (Und somit dieser Block in der DMAP reserviert wird)
 - [x] fuseCreate (Datei erstellen und oeffnen)
    Nutze fuseMknod und fuseOpen.
 - [x] fuseUnlink (Datei loeschen)

**Comment by HannesIlly** [comment]
Muss jetzt noch getestet werden.
