### ISSUE TITLE
FUSE // atime, mtime, ctime definieren

### ISSUE THREAD

**Issue by HannesIlly** [MilanKosticKIT/BetriebssystemeUebung#54]
Es sollte genau nachgeforscht (bzw. definiert) werden, bei welchem Methodenaufruf welche Zugriffszeiten geändert werden sollen.

**Comment by MilanKosticKIT** [comment]
Entweder wir machen es wie wir wollen, oder wie es bereits definiert ist :/

**Comment by MilanKosticKIT** [comment]
Von existierenden die c übernehmen, sonst Zeitpunkt der Erstellung
m time beim ändern
a time kann bei open und read aber definitiv bei read
