### ISSUE TITLE
FUSE // fuseRead

### ISSUE THREAD

**Issue by MilanKosticKIT** [MilanKosticKIT/BetriebssystemeUebung#62]
Aktuell funktioniert die Pufferung noch nicht.
Grund ist eine Fehlerhafte Implementierung um myfs.cpp:361
Achtung: Hauptentwickler sagt es wird wahrscheinlich eine größere Sache.

**Comment by HannesIlly** [comment]
#### Achtung hier kommt das Problem:
Hier der Quellcode aus fuseRead (Der Code ist nur das eigentliche Lesen):
```
char buffer[BLOCK_SIZE];
if (openFiles[fileInfo->fh].bufferBlockNumber == blocks[0]) {
    memcpy(buf, openFiles[fileInfo->fh].buffer + blockOffset, BLOCK_SIZE - (size_t)blockOffset);
    bufferBlockNumber = blocks[0];
} else {
    blockDevice->read(DATA_START + blocks[0], buffer);
    memcpy(buf, buffer + blockOffset, BLOCK_SIZE - (size_t)blockOffset);
}
for (int j = 1; j < howManyBlocks - 1; j++) {
    blockDevice->read(DATA_START + blocks[j], buf - blockOffset + BLOCK_SIZE * j);
}
if (howManyBlocks > 1) {
    blockDevice->read(DATA_START + blocks[howManyBlocks - 1], buffer);
    memcpy(buf - blockOffset + (howManyBlocks - 1) * BLOCK_SIZE, buffer, (size + blockOffset) % BLOCK_SIZE);
    bufferBlockNumber = blocks[howManyBlocks - 1];
}
```
Debugging hat ergeben, dass innerhalb dieses Quellcodes in folgender Zeile der Wert von ``fileInfo->fh`` auf einen ungültigen (zufälligen) Wert geändert wird:
``memcpy(buf, buffer + blockOffset, BLOCK_SIZE - (size_t)blockOffset);`` (Zeile 7)

Wenn jemand weiß wo genau jetzt das Problem ist wäre das gut.

**Comment by HannesIlly** [comment]
In der Read wurde im ersten Block zu viel gelesen, wenn ``blockOffset + size < BLOCK_SIZE``
Dadurch wurde mit memcpy falscher Speicher geschrieben.
Ist jetzt erledigt.
