### ISSUE TITLE
Datenstruktur Initialisierung Daten

### ISSUE THREAD

**Issue by MilanKosticKIT** [MilanKosticKIT/BetriebssystemeUebung#9]
Sollen die Datenstrukturen die Daten selbst von der Hardware lesen oder übergeben bekommen?
Selbige Problemstellung beim Speichern.

**Comment by murmal** [comment]
die datenstrukturen stellen methoden zum befüllen und lesen. diese werden von einer zentralen methode (myfs) benutzt. 
setAll(char* p)
getAll(char *p)
